//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLottoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBallLottery
    {
        public int BallNumber { get; set; }
        public Nullable<int> LotteryID { get; set; }
        public Nullable<int> NbTimesOccured { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual tblLottery tblLottery { get; set; }
    }
}
