//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLottoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQAThread
    {
        public Nullable<System.DateTime> DateTimeOpen { get; set; }
        public string Topic { get; set; }
        public string OpenUser { get; set; }
        public int QAThreadID { get; set; }
    }
}
