//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLottoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReply
    {
        public string UserName { get; set; }
        public Nullable<int> QAThread { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Text { get; set; }
        public int ReplyID { get; set; }
    }
}
