//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLottoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceTicket
    {
        public Nullable<System.DateTime> DateTimeSent { get; set; }
        public Nullable<bool> FlagResolved { get; set; }
        public string IssuedBy { get; set; }
        public string Responsible { get; set; }
        public string Text { get; set; }
        public int SerTicketID { get; set; }
    }
}
