//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLottoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTicket
    {
        public string Lottery { get; set; }
        public Nullable<System.DateTime> DatePlay { get; set; }
        public Nullable<System.DateTime> DateBuy { get; set; }
        public string Combination { get; set; }
        public string Vendor { get; set; }
        public string Buyer { get; set; }
        public int LTID { get; set; }
    }
}
