//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLottoApp.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddress
    {
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string Suburb { get; set; }
        public string SreetNumber { get; set; }
        public Nullable<bool> Validity { get; set; }
        public string UserID { get; set; }
        public int Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
