//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLottoApp.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCombination
    {
        public string Numbers { get; set; }
        public int CombID { get; set; }
        public Nullable<int> SetID { get; set; }
    }
}
