//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLottoApp.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLottery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLottery()
        {
            this.tblBallLotteries = new HashSet<tblBallLottery>();
            this.tblResults = new HashSet<tblResult>();
        }
    
        public string LottoName { get; set; }
        public Nullable<int> NbOfBalls { get; set; }
        public string DayPlay { get; set; }
        public int LotteryID { get; set; }
        public Nullable<int> TotalNbBalls { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBallLottery> tblBallLotteries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblResult> tblResults { get; set; }
    }
}
